version: "3.9"

services:
  app:
    build: .
    container_name: company-app
    # depends_on: - db # Removed, no longer depends on db service
    ports:
      - "3000:3000"      # dashboard & REST
      - "3001:3001"      # WebSocket
    environment:
      # DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-changeme}@db:5432/company # Removed, not using Postgres
      JWT_SECRET:  ${JWT_SECRET:-changeme}
      MIN_WORKERS: ${MIN_WORKERS:-1}
      MAX_WORKERS: ${MAX_WORKERS:-3}
      # Add API keys here if not sourced via .env file inside the container (Dockerfile COPY .)
      # OPENAI_API_KEY: ${OPENAI_API_KEY}
    # hot-reload settings (for development):
    volumes:
      - .:/usr/src/app          # mount source code into container
      - /usr/src/app/node_modules # keep container's node_modules separate from host
    command: npm run dev          # use nodemon via package.json script

# Removed 'volumes: pgdata:' as the db service is gone